import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from "next/link"
import Image from 'next/image'
import { Button } from "@/components/ui/button"
import { MobileNav } from '@/components/ui/mobileNav'
import { Wallet, Menu } from 'lucide-react'
import { Web3ModalProvider } from "../context/Web3Modal";
import { NavConnectButton } from '@/components/ui/walletConnect'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KKC',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ModalProvider>
          <nav className="flex justify-between items-center px-4 md:px-20 py-4 bg-black text-white relative z-10">
            <div className="flex items-center">
              <MobileNav />
              <div className="ml-2 md:ml-0">
                <Image
                  src="/logo.png"
                  alt="KakaoCoin logo"
                  width={120}
                  height={24}
                  priority
                />
              </div>
              <div className="hidden md:flex ml-8">
                <Link href="/" className="text-sm mr-4">
                  HOME
                </Link>
                <Link href="/ico" className="text-sm">
                  ICO
                </Link>
              </div>
            </div>
            <div className="flex items-center">
              <NavConnectButton />
            </div>
          </nav>
          <div className="flex flex-col items-center">
            {children}
          </div>
          <footer className="relative mt-20 bg-[#FFC102] px-8 md:px-32 py-16">
            <div className="absolute left-[5%] transform -translate-y-2/3 top-0">
            <Image 
              src="/footer.png"
              alt="footer bear"
              width={128}
              height={180}
            />
            </div>
            <div className="md:flex justify-between">
              <div className="w-full md:w-1/4 flex flex-col items-center">
                <Image
                  src="/footerLogo.png"
                  alt="KakaoCoin logo"
                  width={240}
                  height={40}
                />
                <p className="mt-6 text-center md:text-left text-sm md:text-base md:text-base">
                  By establishing a truly decentralized social aggregation platform, we aim to pioneer innovative social
                  models and enhance the social experience in the Web3 digital era!
                </p>
              </div>
              <div className="grid grid-cols-3 gap-10 md:gap-4 mt-8 md:mt-0">
                <div>
                  <h3 className="font-bold mb-4">About</h3>
                  <ul className="space-y-2 text-sm md:text-base">
                    <li>
                      <Link className="text-white" href="#">
                        Help
                      </Link>
                    </li>
                    <li>
                      <Link className="text-white" href="#">
                        Partners
                      </Link>
                    </li>
                    <li>
                      <Link className="text-white" href="#">
                        Docs
                      </Link>
                    </li>
                    <li>
                      <Link className="text-white" href="#">
                        Platform status
                      </Link>
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-bold mb-4">Info</h3>
                  <ul className="space-y-2 text-sm md:text-base">
                    <li>
                      <Link className="text-white" href="#">
                        About us
                      </Link>
                    </li>
                    <li>
                      <Link className="text-white" href="#">
                        Privacy Policies
                      </Link>
                    </li>
                    <li>
                      <Link className="text-white" href="#">
                        Terms & Conditions
                      </Link>
                    </li>
                    <li>
                      <Link className="text-white" href="#">
                        Contact us
                      </Link>
                    </li>
                  </ul>
                </div>
                <div>
                  <h3 className="font-bold mb-4">Touch</h3>
                  <div className="flex flex-col md:flex-row space-y-2 md:space-x-2 md:space-y-0">
                    <DiscordIcon />
                    <TwitterIcon  />
                    <TelegramIcon  />
                  </div>
                </div>
              </div>
            </div>
          </footer>
        </Web3ModalProvider>
      </body>
    </html>
  )
}

function DiscordIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="0"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
<path d="M18.59 5.88997C17.36 5.31997 16.05 4.89997 14.67 4.65997C14.5 4.95997 14.3 5.36997 14.17 5.69997C12.71 5.47997 11.26 5.47997 9.83001 5.69997C9.69001 5.36997 9.49001 4.95997 9.32001 4.65997C7.94001 4.89997 6.63001 5.31997 5.40001 5.88997C2.92001 9.62997 2.25001 13.28 2.58001 16.87C4.23001 18.1 5.82001 18.84 7.39001 19.33C7.78001 18.8 8.12001 18.23 8.42001 17.64C7.85001 17.43 7.31001 17.16 6.80001 16.85C6.94001 16.75 7.07001 16.64 7.20001 16.54C10.33 18 13.72 18 16.81 16.54C16.94 16.65 17.07 16.75 17.21 16.85C16.7 17.16 16.15 17.42 15.59 17.64C15.89 18.23 16.23 18.8 16.62 19.33C18.19 18.84 19.79 18.1 21.43 16.87C21.82 12.7 20.76 9.08997 18.61 5.88997H18.59ZM8.84001 14.67C7.90001 14.67 7.13001 13.8 7.13001 12.73C7.13001 11.66 7.88001 10.79 8.84001 10.79C9.80001 10.79 10.56 11.66 10.55 12.73C10.55 13.79 9.80001 14.67 8.84001 14.67ZM15.15 14.67C14.21 14.67 13.44 13.8 13.44 12.73C13.44 11.66 14.19 10.79 15.15 10.79C16.11 10.79 16.87 11.66 16.86 12.73C16.86 13.79 16.11 14.67 15.15 14.67Z" fill="#ffffff"></path> 
    </svg>
  )
}

function TelegramIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 30 30"
      fill="white"
      stroke="currentColor"
      strokeWidth="0"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
    <path d="M29.919 6.163l-4.225 19.925c-0.319 1.406-1.15 1.756-2.331 1.094l-6.438-4.744-3.106 2.988c-0.344 0.344-0.631 0.631-1.294 0.631l0.463-6.556 11.931-10.781c0.519-0.462-0.113-0.719-0.806-0.256l-14.75 9.288-6.35-1.988c-1.381-0.431-1.406-1.381 0.288-2.044l24.837-9.569c1.15-0.431 2.156 0.256 1.781 2.013z"></path>
    </svg>
  )
}


function TwitterIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="white"
      stroke="currentColor"
      strokeWidth="0"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}

